spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
#email config
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=bealucky.dev@gmail.com
#spring.mail.password=vsxuopvmqychmnak
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true   
 
 
  mail:
    host: smtp.gmail.com
    port: 587
    username: bealucky.dev@gmail.com
    password: dbksbnbqjtlpixrl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
    
    
#  mail:
#    host: localhost
#    port: 1025
#    username: lucky
#    password: lucky
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
        
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088
          
    
      
       